name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    name: releaser
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@master
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Run Semantic Release
        id: semantic
        uses: codfish/semantic-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
