name: Slow
on:
  pull_request:

jobs:
  release:
    name: slow
    runs-on: ubuntu-latest
    steps:
      - run: |
          for i in {1..3600}; do
            printf "$i\t"
            date
            sleep 1
          done
